using System.Collections.Generic;

namespace NoSuchStudio.Localization.Database {
    public static class LanguagesData {
        public readonly static IList<Locale> data;
        public readonly static LocaleDatabase database;
        static LanguagesData() {
            var tmpData = new List<Locale>();
            tmpData.Add(new Locale("aa", "Afar", "Qafar", true, "", "aar", false));
            tmpData.Add(new Locale("af", "Afrikaans", "Afrikaans", true, "", "afr", false));
            tmpData.Add(new Locale("agq", "Aghem", "Aghem", true, "", "agq", false));
            tmpData.Add(new Locale("ak", "Akan", "Akan", true, "", "aka", false));
            tmpData.Add(new Locale("am", "Amharic", "አማርኛ", true, "", "amh", false));
            tmpData.Add(new Locale("ar", "Arabic", "العربية", true, "", "ara", true));
            tmpData.Add(new Locale("arn", "Mapudungun", "Mapudungun", true, "", "arn", false));
            tmpData.Add(new Locale("as", "Assamese", "অসমীয়া", true, "", "asm", false));
            tmpData.Add(new Locale("asa", "Asu", "Kipare", true, "", "asa", false));
            tmpData.Add(new Locale("ast", "Asturian", "asturianu", true, "", "ast", false));
            tmpData.Add(new Locale("az", "Azerbaijani", "azərbaycan", true, "", "aze", false));
            tmpData.Add(new Locale("az-Cyrl", "Azerbaijani (Cyrillic)", "Азәрбајҹан дили", true, "az", "aze", false));
            tmpData.Add(new Locale("az-Latn", "Azerbaijani (Latin)", "azərbaycan", true, "az", "aze", false));
            tmpData.Add(new Locale("ba", "Bashkir", "Башҡорт", true, "", "bak", false));
            tmpData.Add(new Locale("bas", "Basaa", "Ɓàsàa", true, "", "bas", false));
            tmpData.Add(new Locale("be", "Belarusian", "Беларуская", true, "", "bel", false));
            tmpData.Add(new Locale("bem", "Bemba", "Ichibemba", true, "", "bem", false));
            tmpData.Add(new Locale("bez", "Bena", "Hibena", true, "", "bez", false));
            tmpData.Add(new Locale("bg", "Bulgarian", "български", true, "", "bul", false));
            tmpData.Add(new Locale("bin", "Edo", "Ẹ̀dó", true, "", "bin", false));
            tmpData.Add(new Locale("bm", "Bamanankan", "bamanakan", true, "", "bam", false));
            tmpData.Add(new Locale("bm-Latn", "Bamanankan (Latin)", "bamanakan", true, "bm", "bam", false));
            tmpData.Add(new Locale("bn", "Bangla", "বাংলা", true, "", "ben", false));
            tmpData.Add(new Locale("bo", "Tibetan", "བོད་ཡིག", true, "", "bod", false));
            tmpData.Add(new Locale("br", "Breton", "brezhoneg", true, "", "bre", false));
            tmpData.Add(new Locale("brx", "Bodo", "बड़ो", true, "", "brx", false));
            tmpData.Add(new Locale("bs", "Bosnian", "bosanski", true, "", "bos", false));
            tmpData.Add(new Locale("bs-Cyrl", "Bosnian (Cyrillic)", "босански", true, "bs", "bos", false));
            tmpData.Add(new Locale("bs-Latn", "Bosnian (Latin)", "bosanski", true, "bs", "bos", false));
            tmpData.Add(new Locale("byn", "Blin", "ብሊን", true, "", "byn", false));
            tmpData.Add(new Locale("ca", "Catalan", "català", true, "", "cat", false));
            tmpData.Add(new Locale("ce", "Chechen", "нохчийн", true, "", "che", false));
            tmpData.Add(new Locale("cgg", "Chiga", "Rukiga", true, "", "cgg", false));
            tmpData.Add(new Locale("chr", "Cherokee", "ᏣᎳᎩ", true, "", "chr", false));
            tmpData.Add(new Locale("chr-Cher", "Cherokee (Cherokee)", "ᏣᎳᎩ", true, "chr", "chr", false));
            tmpData.Add(new Locale("co", "Corsican", "Corsu", true, "", "cos", false));
            tmpData.Add(new Locale("cs", "Czech", "čeština", true, "", "ces", false));
            tmpData.Add(new Locale("cu", "Church Slavic", "церковнослове́нскїй", true, "", "chu", false));
            tmpData.Add(new Locale("cy", "Welsh", "Cymraeg", true, "", "cym", false));
            tmpData.Add(new Locale("da", "Danish", "dansk", true, "", "dan", false));
            tmpData.Add(new Locale("dav", "Taita", "Kitaita", true, "", "dav", false));
            tmpData.Add(new Locale("de", "German", "Deutsch", true, "", "deu", false));
            tmpData.Add(new Locale("dje", "Zarma", "Zarmaciine", true, "", "dje", false));
            tmpData.Add(new Locale("dsb", "Lower Sorbian", "dolnoserbšćina", true, "hsb", "dsb", false));
            tmpData.Add(new Locale("dua", "Duala", "duálá", true, "", "dua", false));
            tmpData.Add(new Locale("dv", "Divehi", "ދިވެހިބަސް", true, "", "div", true));
            tmpData.Add(new Locale("dyo", "Jola-Fonyi", "joola", true, "", "dyo", false));
            tmpData.Add(new Locale("dz", "Dzongkha", "རྫོང་ཁ", true, "", "dzo", false));
            tmpData.Add(new Locale("ebu", "Embu", "Kĩembu", true, "", "ebu", false));
            tmpData.Add(new Locale("ee", "Ewe", "Eʋegbe", true, "", "ewe", false));
            tmpData.Add(new Locale("el", "Greek", "Ελληνικά", true, "", "ell", false));
            tmpData.Add(new Locale("en", "English", "English", true, "", "eng", false));
            tmpData.Add(new Locale("eo", "Esperanto", "esperanto", true, "", "epo", false));
            tmpData.Add(new Locale("es", "Spanish", "español", true, "", "spa", false));
            tmpData.Add(new Locale("et", "Estonian", "eesti", true, "", "est", false));
            tmpData.Add(new Locale("eu", "Basque", "euskara", true, "", "eus", false));
            tmpData.Add(new Locale("ewo", "Ewondo", "ewondo", true, "", "ewo", false));
            tmpData.Add(new Locale("fa", "Persian", "فارسی", true, "", "fas", true));
            tmpData.Add(new Locale("ff", "Fulah", "Pulaar", true, "", "ful", false));
            tmpData.Add(new Locale("ff-Latn", "Fulah (Latin)", "Pulaar", true, "ff", "ful", false));
            tmpData.Add(new Locale("fi", "Finnish", "suomi", true, "", "fin", false));
            tmpData.Add(new Locale("fil", "Filipino", "Filipino", true, "", "fil", false));
            tmpData.Add(new Locale("fo", "Faroese", "føroyskt", true, "", "fao", false));
            tmpData.Add(new Locale("fr", "French", "français", true, "", "fra", false));
            tmpData.Add(new Locale("fur", "Friulian", "furlan", true, "", "fur", false));
            tmpData.Add(new Locale("fy", "Western Frisian", "Frysk", true, "", "fry", false));
            tmpData.Add(new Locale("ga", "Irish", "Gaeilge", true, "", "gle", false));
            tmpData.Add(new Locale("gd", "Scottish Gaelic", "Gàidhlig", true, "", "gla", false));
            tmpData.Add(new Locale("gl", "Galician", "galego", true, "", "glg", false));
            tmpData.Add(new Locale("gn", "Guarani", "Avañe’ẽ", true, "", "grn", false));
            tmpData.Add(new Locale("gsw", "Swiss German", "Schwiizertüütsch", true, "", "gsw", false));
            tmpData.Add(new Locale("gu", "Gujarati", "ગુજરાતી", true, "", "guj", false));
            tmpData.Add(new Locale("guz", "Gusii", "Ekegusii", true, "", "guz", false));
            tmpData.Add(new Locale("gv", "Manx", "Gaelg", true, "", "glv", false));
            tmpData.Add(new Locale("ha", "Hausa", "Hausa", true, "", "hau", false));
            tmpData.Add(new Locale("ha-Latn", "Hausa (Latin)", "Hausa", true, "ha", "hau", false));
            tmpData.Add(new Locale("haw", "Hawaiian", "ʻŌlelo Hawaiʻi", true, "", "haw", false));
            tmpData.Add(new Locale("he", "Hebrew", "עברית", true, "", "heb", true));
            tmpData.Add(new Locale("hi", "Hindi", "हिन्दी", true, "", "hin", false));
            tmpData.Add(new Locale("hr", "Croatian", "hrvatski", true, "", "hrv", false));
            tmpData.Add(new Locale("hsb", "Upper Sorbian", "hornjoserbšćina", true, "", "hsb", false));
            tmpData.Add(new Locale("hu", "Hungarian", "magyar", true, "", "hun", false));
            tmpData.Add(new Locale("hy", "Armenian", "Հայերեն", true, "", "hye", false));
            tmpData.Add(new Locale("ia", "Interlingua", "interlingua", true, "", "ina", false));
            tmpData.Add(new Locale("ibb", "Ibibio", "Ibibio-Efik", true, "", "ibb", false));
            tmpData.Add(new Locale("id", "Indonesian", "Indonesia", true, "", "ind", false));
            tmpData.Add(new Locale("ig", "Igbo", "Igbo", true, "", "ibo", false));
            tmpData.Add(new Locale("ii", "Yi", "ꆈꌠꁱꂷ", true, "", "iii", false));
            tmpData.Add(new Locale("is", "Icelandic", "íslenska", true, "", "isl", false));
            tmpData.Add(new Locale("it", "Italian", "italiano", true, "", "ita", false));
            tmpData.Add(new Locale("iu", "Inuktitut", "Inuktitut", true, "", "iku", false));
            tmpData.Add(new Locale("iu-Cans", "Inuktitut (Syllabics)", "ᐃᓄᒃᑎᑐᑦ", true, "iu", "iku", false));
            tmpData.Add(new Locale("iu-Latn", "Inuktitut (Latin)", "Inuktitut", true, "iu", "iku", false));
            tmpData.Add(new Locale("ja", "Japanese", "日本語", true, "", "jpn", false));
            tmpData.Add(new Locale("jgo", "Ngomba", "Ndaꞌa", true, "", "jgo", false));
            tmpData.Add(new Locale("jmc", "Machame", "Kimachame", true, "", "jmc", false));
            tmpData.Add(new Locale("jv", "Javanese", "Basa Jawa", true, "", "jav", false));
            tmpData.Add(new Locale("jv-Java", "Javanese (Javanese)", "ꦧꦱꦗꦮ", true, "jv", "jav", false));
            tmpData.Add(new Locale("jv-Latn", "Javanese (Latin)", "Basa Jawa", true, "jv", "jav", false));
            tmpData.Add(new Locale("ka", "Georgian", "ქართული", true, "", "kat", false));
            tmpData.Add(new Locale("kab", "Kabyle", "Taqbaylit", true, "", "kab", false));
            tmpData.Add(new Locale("kam", "Kamba", "Kikamba", true, "", "kam", false));
            tmpData.Add(new Locale("kde", "Makonde", "Chimakonde", true, "", "kde", false));
            tmpData.Add(new Locale("kea", "Kabuverdianu", "kabuverdianu", true, "", "kea", false));
            tmpData.Add(new Locale("khq", "Koyra Chiini", "Koyra ciini", true, "", "khq", false));
            tmpData.Add(new Locale("ki", "Kikuyu", "Gikuyu", true, "", "kik", false));
            tmpData.Add(new Locale("kk", "Kazakh", "қазақ тілі", true, "", "kaz", false));
            tmpData.Add(new Locale("kkj", "Kako", "kakɔ", true, "", "kkj", false));
            tmpData.Add(new Locale("kl", "Greenlandic", "kalaallisut", true, "", "kal", false));
            tmpData.Add(new Locale("kln", "Kalenjin", "Kalenjin", true, "", "kln", false));
            tmpData.Add(new Locale("km", "Khmer", "ភាសាខ្មែរ", true, "", "khm", false));
            tmpData.Add(new Locale("kn", "Kannada", "ಕನ್ನಡ", true, "", "kan", false));
            tmpData.Add(new Locale("ko", "Korean", "한국어", true, "", "kor", false));
            tmpData.Add(new Locale("kok", "Konkani", "कोंकणी", true, "", "kok", false));
            tmpData.Add(new Locale("kr", "Kanuri", "Kanuri", true, "", "kau", false));
            tmpData.Add(new Locale("kr-Latn", "Kanuri (Latin)", "Kanuri", true, "kr", "kau", false));
            tmpData.Add(new Locale("ks", "Kashmiri", "کٲشُر", true, "", "kas", false));
            tmpData.Add(new Locale("ks-Arab", "Kashmiri (Perso-Arabic)", "کٲشُر", true, "ks", "kas", false));
            tmpData.Add(new Locale("ks-Deva", "Kashmiri (Devanagari)", "कॉशुर", true, "ks", "kas", false));
            tmpData.Add(new Locale("ksb", "Shambala", "Kishambaa", true, "", "ksb", false));
            tmpData.Add(new Locale("ksf", "Bafia", "rikpa", true, "", "ksf", false));
            tmpData.Add(new Locale("ksh", "Colognian", "Kölsch", true, "", "ksh", false));
            tmpData.Add(new Locale("ku", "Central Kurdish", "کوردیی ناوەڕاست", true, "", "kur", true));
            tmpData.Add(new Locale("ku-Arab", "Central Kurdish (Perso-Arabic)", "کوردیی ناوەڕاست", true, "ku", "kur", true));
            tmpData.Add(new Locale("kw", "Cornish", "kernewek", true, "", "cor", false));
            tmpData.Add(new Locale("ky", "Kyrgyz", "Кыргыз", true, "", "kir", false));
            tmpData.Add(new Locale("la", "Latin", "lingua latīna", true, "", "lat", false));
            tmpData.Add(new Locale("lag", "Langi", "Kɨlaangi", true, "", "lag", false));
            tmpData.Add(new Locale("lb", "Luxembourgish", "Lëtzebuergesch", true, "", "ltz", false));
            tmpData.Add(new Locale("lg", "Ganda", "Luganda", true, "", "lug", false));
            tmpData.Add(new Locale("lkt", "Lakota", "Lakȟólʼiyapi", true, "", "lkt", false));
            tmpData.Add(new Locale("ln", "Lingala", "lingála", true, "", "lin", false));
            tmpData.Add(new Locale("lo", "Lao", "ລາວ", true, "", "lao", false));
            tmpData.Add(new Locale("lrc", "Northern Luri", "لۊری شومالی", true, "", "lrc", false));
            tmpData.Add(new Locale("lt", "Lithuanian", "lietuvių", true, "", "lit", false));
            tmpData.Add(new Locale("lu", "Luba-Katanga", "Tshiluba", true, "", "lub", false));
            tmpData.Add(new Locale("luo", "Luo", "Dholuo", true, "", "luo", false));
            tmpData.Add(new Locale("luy", "Luyia", "Luluhia", true, "", "luy", false));
            tmpData.Add(new Locale("lv", "Latvian", "latviešu", true, "", "lav", false));
            tmpData.Add(new Locale("mas", "Masai", "Maa", true, "", "mas", false));
            tmpData.Add(new Locale("mer", "Meru", "Kĩmĩrũ", true, "", "mer", false));
            tmpData.Add(new Locale("mfe", "Morisyen", "kreol morisien", true, "", "mfe", false));
            tmpData.Add(new Locale("mg", "Malagasy", "Malagasy", true, "", "mlg", false));
            tmpData.Add(new Locale("mgh", "Makhuwa-Meetto", "Makua", true, "", "mgh", false));
            tmpData.Add(new Locale("mgo", "Metaʼ", "metaʼ", true, "", "mgo", false));
            tmpData.Add(new Locale("mi", "Maori", "te reo Māori", true, "", "mri", false));
            tmpData.Add(new Locale("mk", "Macedonian", "македонски", true, "", "mkd", false));
            tmpData.Add(new Locale("ml", "Malayalam", "മലയാളം", true, "", "mal", false));
            tmpData.Add(new Locale("mn", "Mongolian", "монгол", true, "", "mon", false));
            tmpData.Add(new Locale("mn-Cyrl", "Mongolian (Cyrillic)", "монгол", true, "mn", "mon", false));
            tmpData.Add(new Locale("mn-Mong", "Mongolian (Traditional Mongolian)", "ᠮᠣᠩᠭᠣᠤᠯ ᠬᠡᠯᠡ", true, "mn", "mon", false));
            tmpData.Add(new Locale("mni", "Manipuri", "মৈতৈলোন্", true, "", "mni", false));
            tmpData.Add(new Locale("moh", "Mohawk", "Kanien’kéha", true, "", "moh", false));
            tmpData.Add(new Locale("mr", "Marathi", "मराठी", true, "", "mar", false));
            tmpData.Add(new Locale("ms", "Malay", "Melayu", true, "", "msa", false));
            tmpData.Add(new Locale("mt", "Maltese", "Malti", true, "", "mlt", false));
            tmpData.Add(new Locale("mua", "Mundang", "MUNDAŊ", true, "", "mua", false));
            tmpData.Add(new Locale("my", "Burmese", "ဗမာ", true, "", "mya", false));
            tmpData.Add(new Locale("mzn", "Mazanderani", "مازرونی", true, "", "mzn", false));
            tmpData.Add(new Locale("naq", "Nama", "Khoekhoegowab", true, "", "naq", false));
            tmpData.Add(new Locale("nb", "Norwegian Bokmål", "norsk bokmål", true, "no", "nob", false));
            tmpData.Add(new Locale("nd", "North Ndebele", "isiNdebele", true, "", "nde", false));
            tmpData.Add(new Locale("nds", "Low German", "Neddersass’sch", true, "", "nds", false));
            tmpData.Add(new Locale("ne", "Nepali", "नेपाली", true, "", "nep", false));
            tmpData.Add(new Locale("nl", "Dutch", "Nederlands", true, "", "nld", false));
            tmpData.Add(new Locale("nmg", "Kwasio", "Kwasio", true, "", "nmg", false));
            tmpData.Add(new Locale("nn", "Norwegian Nynorsk", "nynorsk", true, "no", "nno", false));
            tmpData.Add(new Locale("nnh", "Ngiemboon", "Shwóŋò ngiembɔɔn", true, "", "nnh", false));
            tmpData.Add(new Locale("no", "Norwegian", "norsk", true, "", "nob", false));
            tmpData.Add(new Locale("nqo", "N'ko", "ߒߞߏ", true, "", "nqo", true));
            tmpData.Add(new Locale("nr", "South Ndebele", "isiNdebele", true, "", "nbl", false));
            tmpData.Add(new Locale("nso", "Sesotho sa Leboa", "Sesotho sa Leboa", true, "", "nso", false));
            tmpData.Add(new Locale("nus", "Nuer", "Thok Nath", true, "", "nus", false));
            tmpData.Add(new Locale("nyn", "Nyankole", "Runyankore", true, "", "nyn", false));
            tmpData.Add(new Locale("oc", "Occitan", "Occitan", true, "", "oci", false));
            tmpData.Add(new Locale("om", "Oromo", "Oromoo", true, "", "orm", false));
            tmpData.Add(new Locale("or", "Odia", "ଓଡ଼ିଆ", true, "", "ori", false));
            tmpData.Add(new Locale("os", "Ossetic", "ирон", true, "", "oss", false));
            tmpData.Add(new Locale("pa", "Punjabi", "ਪੰਜਾਬੀ", true, "", "pan", false));
            tmpData.Add(new Locale("pa-Arab", "Punjabi (Perso-Arabic)", "پنجابی", true, "pa", "pan", true));
            tmpData.Add(new Locale("pa-Guru", "Punjabi (Punjabi)", "ਪੰਜਾਬੀ", true, "pa", "pan", false));
            tmpData.Add(new Locale("pap", "Papiamento", "Papiamentu", true, "", "pap", false));
            tmpData.Add(new Locale("pl", "Polish", "polski", true, "", "pol", false));
            tmpData.Add(new Locale("prg", "Prussian", "prūsiskan", true, "", "prg", false));
            tmpData.Add(new Locale("prs", "Dari", "درى", true, "", "prs", true));
            tmpData.Add(new Locale("ps", "Pashto", "پښتو", true, "", "pus", true));
            tmpData.Add(new Locale("pt", "Portuguese", "português", true, "", "por", false));
            tmpData.Add(new Locale("quc", "K'iche'", "K'iche'", true, "", "quc", false));
            tmpData.Add(new Locale("quc-Latn", "K'iche' (Latin)", "K'iche'", true, "quc", "quc", false));
            tmpData.Add(new Locale("quz", "Quechua", "Runasimi", true, "", "qub", false));
            tmpData.Add(new Locale("rm", "Romansh", "rumantsch", true, "", "roh", false));
            tmpData.Add(new Locale("rn", "Rundi", "Ikirundi", true, "", "run", false));
            tmpData.Add(new Locale("ro", "Romanian", "română", true, "", "ron", false));
            tmpData.Add(new Locale("rof", "Rombo", "Kihorombo", true, "", "rof", false));
            tmpData.Add(new Locale("ru", "Russian", "русский", true, "", "rus", false));
            tmpData.Add(new Locale("rw", "Kinyarwanda", "Kinyarwanda", true, "", "kin", false));
            tmpData.Add(new Locale("rwk", "Rwa", "Kiruwa", true, "", "rwk", false));
            tmpData.Add(new Locale("sa", "Sanskrit", "संस्कृत", true, "", "san", false));
            tmpData.Add(new Locale("sah", "Sakha", "Саха", true, "", "sah", false));
            tmpData.Add(new Locale("saq", "Samburu", "Kisampur", true, "", "saq", false));
            tmpData.Add(new Locale("sbp", "Sangu", "Ishisangu", true, "", "sbp", false));
            tmpData.Add(new Locale("sd", "Sindhi", "سنڌي", true, "", "snd", true));
            tmpData.Add(new Locale("sd-Arab", "Sindhi (Perso-Arabic)", "سنڌي", true, "sd", "snd", true));
            tmpData.Add(new Locale("sd-Deva", "Sindhi (Devanagari)", "सिन्धी", true, "sd", "snd", false));
            tmpData.Add(new Locale("se", "Northern Sami", "davvisámegiella", true, "", "sme", false));
            tmpData.Add(new Locale("seh", "Sena", "sena", true, "", "seh", false));
            tmpData.Add(new Locale("ses", "Koyraboro Senni", "Koyraboro senni", true, "", "ses", false));
            tmpData.Add(new Locale("sg", "Sango", "Sängö", true, "", "sag", false));
            tmpData.Add(new Locale("shi", "Tachelhit", "ⵜⴰⵛⵍⵃⵉⵜ", true, "", "shi", false));
            tmpData.Add(new Locale("shi-Latn", "Tachelhit (Latin)", "Tashelḥiyt", true, "shi", "shi", false));
            tmpData.Add(new Locale("shi-Tfng", "Tachelhit (Tifinagh)", "ⵜⴰⵛⵍⵃⵉⵜ", true, "shi", "shi", false));
            tmpData.Add(new Locale("si", "Sinhala", "සිංහල", true, "", "sin", false));
            tmpData.Add(new Locale("sk", "Slovak", "slovenčina", true, "", "slk", false));
            tmpData.Add(new Locale("sl", "Slovenian", "slovenščina", true, "", "slv", false));
            tmpData.Add(new Locale("sma", "Sami (Southern)", "åarjelsaemiengïele", true, "se", "sma", false));
            tmpData.Add(new Locale("smj", "Sami (Lule)", "julevusámegiella", true, "se", "smj", false));
            tmpData.Add(new Locale("smn", "Sami (Inari)", "anarâškielâ", true, "se", "smn", false));
            tmpData.Add(new Locale("sms", "Sami (Skolt)", "sää´mǩiõll", true, "se", "sms", false));
            tmpData.Add(new Locale("sn", "Shona", "chiShona", true, "", "sna", false));
            tmpData.Add(new Locale("sn-Latn", "Shona (Latin)", "chiShona (Latin)", true, "sn", "sna", false));
            tmpData.Add(new Locale("so", "Somali", "Soomaali", true, "", "som", false));
            tmpData.Add(new Locale("sq", "Albanian", "shqip", true, "", "sqi", false));
            tmpData.Add(new Locale("sr", "Serbian", "srpski", true, "", "srp", false));
            tmpData.Add(new Locale("sr-Cyrl", "Serbian (Cyrillic)", "српски", true, "sr", "srp", false));
            tmpData.Add(new Locale("sr-Latn", "Serbian (Latin)", "srpski", true, "sr", "srp", false));
            tmpData.Add(new Locale("ss", "siSwati", "Siswati", true, "", "ssw", false));
            tmpData.Add(new Locale("ssy", "Saho", "Saho", true, "", "ssy", false));
            tmpData.Add(new Locale("st", "Sesotho", "Sesotho", true, "", "sot", false));
            tmpData.Add(new Locale("sv", "Swedish", "svenska", true, "", "swe", false));
            tmpData.Add(new Locale("sw", "Kiswahili", "Kiswahili", true, "", "swa", false));
            tmpData.Add(new Locale("syr", "Syriac", "ܣܘܪܝܝܐ", true, "", "syr", true));
            tmpData.Add(new Locale("ta", "Tamil", "தமிழ்", true, "", "tam", false));
            tmpData.Add(new Locale("te", "Telugu", "తెలుగు", true, "", "tel", false));
            tmpData.Add(new Locale("teo", "Teso", "Kiteso", true, "", "teo", false));
            tmpData.Add(new Locale("tg", "Tajik", "Тоҷикӣ", true, "", "tgk", false));
            tmpData.Add(new Locale("tg-Cyrl", "Tajik (Cyrillic)", "тоҷикӣ", true, "tg", "tgk", false));
            tmpData.Add(new Locale("th", "Thai", "ไทย", true, "", "tha", false));
            tmpData.Add(new Locale("ti", "Tigrinya", "ትግርኛ", true, "", "tir", false));
            tmpData.Add(new Locale("tig", "Tigre", "ትግረ", true, "", "tig", false));
            tmpData.Add(new Locale("tk", "Turkmen", "Türkmen dili", true, "", "tuk", false));
            tmpData.Add(new Locale("tn", "Setswana", "Setswana", true, "", "tsn", false));
            tmpData.Add(new Locale("to", "Tongan", "lea fakatonga", true, "", "ton", false));
            tmpData.Add(new Locale("tr", "Turkish", "Türkçe", true, "", "tur", false));
            tmpData.Add(new Locale("ts", "Tsonga", "Xitsonga", true, "", "tso", false));
            tmpData.Add(new Locale("tt", "Tatar", "Татар", true, "", "tat", false));
            tmpData.Add(new Locale("twq", "Tasawaq", "Tasawaq senni", true, "", "twq", false));
            tmpData.Add(new Locale("tzm", "Central Atlas Tamazight", "Tamaziɣt n laṭlaṣ", true, "", "tzm", false));
            tmpData.Add(new Locale("tzm-Arab", "Central Atlas Tamazight (Arabic)", "أطلس المركزية التامازيتية", true, "tzm", "tzm", true));
            tmpData.Add(new Locale("tzm-Latn", "Central Atlas Tamazight (Latin)", "Tamaziɣt n laṭlaṣ", true, "tzm", "tzm", false));
            tmpData.Add(new Locale("tzm-Tfng", "Central Atlas Tamazight (Tifinagh)", "ⵜⴰⵎⴰⵣⵉⵖⵜ", true, "tzm", "tzm", false));
            tmpData.Add(new Locale("ug", "Uyghur", "ئۇيغۇرچە", true, "", "uig", true));
            tmpData.Add(new Locale("uk", "Ukrainian", "українська", true, "", "ukr", false));
            tmpData.Add(new Locale("ur", "Urdu", "اُردو", true, "", "urd", true));
            tmpData.Add(new Locale("uz", "Uzbek", "o‘zbek", true, "", "uzb", false));
            tmpData.Add(new Locale("uz-Arab", "Uzbek (Perso-Arabic)", "اوزبیک", true, "uz", "uzb", false));
            tmpData.Add(new Locale("uz-Cyrl", "Uzbek (Cyrillic)", "ўзбекча", true, "uz", "uzb", false));
            tmpData.Add(new Locale("uz-Latn", "Uzbek (Latin)", "o‘zbek", true, "uz", "uzb", false));
            tmpData.Add(new Locale("vai", "Vai", "ꕙꔤ", true, "", "vai", false));
            tmpData.Add(new Locale("vai-Latn", "Vai (Latin)", "Vai", true, "vai", "vai", false));
            tmpData.Add(new Locale("vai-Vaii", "Vai (Vai)", "ꕙꔤ", true, "vai", "vai", false));
            tmpData.Add(new Locale("ve", "Venda", "Tshivenḓa", true, "", "ven", false));
            tmpData.Add(new Locale("vi", "Vietnamese", "Tiếng Việt", true, "", "vie", false));
            tmpData.Add(new Locale("vo", "Volapük", "Volapük", true, "", "vol", false));
            tmpData.Add(new Locale("vun", "Vunjo", "Kyivunjo", true, "", "vun", false));
            tmpData.Add(new Locale("wae", "Walser", "Walser", true, "", "wae", false));
            tmpData.Add(new Locale("wal", "Wolaytta", "ወላይታቱ", true, "", "wal", false));
            tmpData.Add(new Locale("wo", "Wolof", "Wolof", true, "", "wol", false));
            tmpData.Add(new Locale("xh", "isiXhosa", "isiXhosa", true, "", "xho", false));
            tmpData.Add(new Locale("xog", "Soga", "Olusoga", true, "", "xog", false));
            tmpData.Add(new Locale("yav", "Yangben", "nuasue", true, "", "yav", false));
            tmpData.Add(new Locale("yi", "Yiddish", "ייִדיש", true, "", "yid", true));
            tmpData.Add(new Locale("yo", "Yoruba", "Èdè Yorùbá", true, "", "yor", false));
            tmpData.Add(new Locale("zgh", "Standard Moroccan Tamazight", "ⵜⴰⵎⴰⵣⵉⵖⵜ", true, "", "zgh", false));
            tmpData.Add(new Locale("zgh-Tfng", "Standard Moroccan Tamazight (Tifinagh)", "ⵜⴰⵎⴰⵣⵉⵖⵜ", true, "zgh", "zgh", false));
            tmpData.Add(new Locale("zh", "Chinese", "中文", true, "", "zho", false));
            tmpData.Add(new Locale("zh-Hans", "Chinese (Simplified)", "中文(简体)", true, "zh", "zho", false));
            tmpData.Add(new Locale("zh-Hant", "Chinese (Traditional)", "中文(繁體)", true, "zh", "zho", false));
            tmpData.Add(new Locale("zu", "isiZulu", "isiZulu", true, "", "zul", false));

            data = tmpData.AsReadOnly();

            database = new LocaleDatabase();
            database.LoadFromCollection(tmpData);
        }
    }
}
